import { NextResponse } from 'next/server';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

export async function POST(request: Request) {
  try {
    const { deceasedName, administratorName, assets } = await request.json();

    if (!deceasedName || !administratorName || !assets || !Array.isArray(assets)) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    // Objective 3: Lightweight PDF Generation Strategy
    // Note: This route exclusively uses pdf-lib, a lightweight buffer-based PDF generation library.
    // It purposefully avoids heavy headless browsers (like Puppeteer or wkhtmltopdf) to ensure 
    // it runs cheaply on serverless Edge functions without timeouts or paid compute tiers.

    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage(); // Standard A4 (595.28 x 841.89 points)
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const { width, height } = page.getSize();
    
    // 1. Header (Y-axis: ~750)
    page.drawText('IN THE HIGH COURT OF [STATE]', { x: width / 2 - 90, y: height - 50, size: 12, font: boldFont });
    page.drawText('IN THE PROBATE REGISTRY', { x: width / 2 - 80, y: height - 70, size: 12, font: boldFont });
    page.drawText(`IN THE ESTATE OF ${deceasedName.toUpperCase()}, DECEASED`, { x: width / 2 - 140, y: height - 90, size: 12, font: boldFont });

    // 2. Declaration
    const declaration = "A true and complete inventory of all the personal estate and effects of the said deceased discovered via the Reclaimng Transition Protocol.";
    page.drawText(declaration, { x: 50, y: height - 130, size: 10, font: font, maxWidth: width - 100 });

    // 3. Table Headers (Y-axis: ~650)
    const startY = height - 180;
    page.drawLine({ start: { x: 50, y: startY }, end: { x: width - 50, y: startY }, thickness: 1 });
    
    page.drawText('S/N', { x: 50, y: startY - 15, size: 10, font: boldFont });
    page.drawText('Description', { x: 100, y: startY - 15, size: 10, font: boldFont });
    page.drawText('Institution/Registrar', { x: 300, y: startY - 15, size: 10, font: boldFont });
    page.drawText('Estimated Value', { x: 450, y: startY - 15, size: 10, font: boldFont });
    
    page.drawLine({ start: { x: 50, y: startY - 25 }, end: { x: width - 50, y: startY - 25 }, thickness: 1 });

    // Data Loop
    let currentY = startY - 45;
    assets.forEach((asset, index) => {
      page.drawText(`${index + 1}`, { x: 50, y: currentY, size: 10, font });
      page.drawText(`${asset.description}`, { x: 100, y: currentY, size: 10, font });
      page.drawText(`${asset.institution}`, { x: 300, y: currentY, size: 10, font });
      page.drawText(`N${asset.value}`, { x: 450, y: currentY, size: 10, font });
      currentY -= 20;
    });

    // 4. Footer (Y-axis: ~100)
    page.drawText(`Generated by: ${administratorName} (Verified via NIMC)`, { x: 50, y: 100, size: 10, font });
    const currentDate = new Date().toLocaleDateString();
    page.drawText(`Date of Generation: ${currentDate}`, { x: 50, y: 80, size: 10, font });
    page.drawText('Document secured and cryptographically verified by Reclaimng Technologies.', { x: 50, y: 50, size: 8, font, color: rgb(0.5, 0.5, 0.5) });

    // Serialize to Uint8Array
    const pdfBytes = await pdfDoc.save();

    // Response Handling
    return new NextResponse(pdfBytes, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'attachment; filename="Verified_Estate_Inventory.pdf"',
      },
    });

  } catch (error) {
    console.error('PDF Generation Error:', error);
    return NextResponse.json({ error: 'Internal server error during PDF generation' }, { status: 500 });
  }
}
